# Markdownlint configuration for Multivac42

default: true

# 允許較長的行（中文內容）
MD013:
  line_length: 200
  code_blocks: false
  tables: false

# 允許 HTML
MD033: false

# 允許重複標題
MD024:
  siblings_only: true

# 允許第一行不是標題
MD041: false
